### ISSUE TITLE
`Bad TOML data`

### ISSUE THREAD

**Issue by Laura7089** [tobealive/wthrr-the-weathercrab#52]
I'm getting an error using the application, I suspect a schema change upstream. I get:

```
Error: Bad TOML data

Caused by:
    invalid type: string "celsius,kmh", expected struct Units for key `units` at line 1 column 9
```

**Comment by tobealive** [comment]
Hey @Laura7089

Confy provides a nice indicator in its errors message what is wrong here.
The config changed some versions ago.

As some more configurable units were added the specifications are now key value pairs per unit in a `units` table. 

The example from the Readme:
```toml
[units]
temperature = 'celsius' # Temperature units: 'celsius' | 'fahrenheit'
speed = 'kmh' # (Wind)speed units: 'kmh' | 'mph' | 'knots' | 'ms'
time = 'military' # Time Format: 'military' | 'ap_pm'
precipitation = 'mm' # Precipitation units 'mm' | 'inch'
```
